version: '3.6'
services:
  mysqldb:
    image: 'mysql:latest'
    container_name: 'mysql-latest'
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: '06_spring_data_jpa'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 06_spring_data_jpa:/var/lib/mysql
volumes:
  06_spring_data_jpa:
