spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
  datasource:
    initialization-mode: always
    url: 'jdbc:mysql://localhost:3306/06_spring_data_jpa'
    username: 'root'
    password: ''
